---
title: "Modeling, Programming and Machine Learning for Financial Analysis"
format: html
sidebar:
    contents:
      - section: "Notebooks"
        contents: 
          - notebooks/cross-validation.ipynb
---

## Introduction to Machine Learning

- [Slides](slides/intro_ml.qmd)

### Reading

- James, G., Witten, D., Hastie, T., Tibshirani, R., & Taylor, J. (2023). *An introduction to statistical learning: With applications in Python.* Springer. [https://www.statlearning.com](https://www.statlearning.com)
  - Chapter 5: Resampling Methods

### Exercises
- [Exercise 1](https://colab.research.google.com/github/fonsecamig/mpaaaf_course/blob/main/notebooks/exerc_kfold_cv.ipynb)

## Decision Trees

### Decision trees

- [Slides](slides/decision_trees.qmd)

### Ensemble Methods

- [Slides](slides/advanced_decision_trees.qmd)

### Reading

- James, G., Witten, D., Hastie, T., Tibshirani, R., & Taylor, J. (2023). *An introduction to statistical learning: With applications in Python.* Springer. [https://www.statlearning.com](https://www.statlearning.com)
  - Chapter 8: Tree-Based Methods

### Exercises
- [Exercise 1](https://colab.research.google.com/github/fonsecamig/mpaaaf_course/blob/main/notebooks/exerc_decision_trees_01.ipynb)
- [Exercise 2](https://colab.research.google.com/github/fonsecamig/mpaaaf_course/blob/main/notebooks/exerc_decision_trees_02.ipynb)

## Feed-Forward Neural Networks

- [Slides](slides/feed_forward_neural_networks.qmd)

### Reading

- Bishop, C. M., & Bishop, H. (2024). *Deep learning: Foundations and concepts.* Springer. [https://www.bishopbook.com](https://www.bishopbook.com)
  - Chapter 6: Deep Neural Networks
  - Chapter 7: Gradient Descent
  - Chapter 8: Backpropagation
- Chollet, F. (2021). *Deep learning with Python (2nd ed.).* Manning Publications.
  - Chapter 2: The mathematical building blocks of neural networks
  - Chapter 4: Getting started with neural networks: Classification and regression
- James, G., Witten, D., Hastie, T., Tibshirani, R., & Taylor, J. (2023). *An introduction to statistical learning: With applications in Python.* Springer. [https://www.statlearning.com](https://www.statlearning.com)
  - Chapter 10: Deep Learning
- Zhang, A., Lipton, Z. C., Li, M., & Smola, A. J. (2023). *Dive into deep learning.* Cambridge University Press. [https://d2l.ai](https://d2l.ai)
  - Chapter 3: Linear Neural Networks for Regression
  - Chapter 4: Linear Neural Networks for Classification
  - Chapter 5: Multilayer Perceptrons

### Exercises

- [Exercise 1](https://colab.research.google.com/github/fonsecamig/mpaaaf_course/blob/main/notebooks/exerc_xor_sgd.ipynb)

## TensorFlow 2

- [Slides](slides/intro_tensorflow2.qmd)

### Reading

- Chollet, F. (2021). *Deep learning with Python (2nd ed.).* Manning Publications.
  - Chapter 3: Introduction to Keras and TensorFlow
  - Chapter 7: Working with Keras: A deep dive
- [https://www.tensorflow.org/tutorials/quickstart/beginner](https://www.tensorflow.org/tutorials/quickstart/beginner)
- [https://www.tensorflow.org/tutorials/keras/classification](https://www.tensorflow.org/tutorials/keras/classification)
- [https://www.tensorflow.org/guide/keras](https://www.tensorflow.org/guide/keras)

### Exercises

- [Exercise 1](https://colab.research.google.com/github/fonsecamig/mpaaaf_course/blob/main/notebooks/exerc_tf2-intro.ipynb)
- [Exercise 2](https://colab.research.google.com/github/fonsecamig/mpaaaf_course/blob/main/notebooks/exerc-mlp-mnist.ipynb)

## Hyperparameter Tuning & Regularisation

### Hyperparameter Tuning

- [Slides](slides/hyperparameter_tuning.qmd)

### Regularisation

- [Slides](slides/regularization.qmd)

### Reading

- Bishop, C. M., & Bishop, H. (2024). *Deep learning: Foundations and concepts.* Springer. [https://www.bishopbook.com](https://www.bishopbook.com)
  - Chapter 9: Regularisation
- Chollet, F. (2021). *Deep learning with Python (2nd ed.).* Manning Publications.
  - Chapter 5: Fundamentals of machine learning
  - Chapter 13: Best practices for the real world, Section 1.1
- Zhang, A., Lipton, Z. C., Li, M., & Smola, A. J. (2023). *Dive into deep learning.* Cambridge University Press. [https://d2l.ai](https://d2l.ai)
  - [Chapter 19: Hyperparameter Optimization](https://d2l.ai/chapter_hyperparameter-optimization/index.html)
- [Deep Learning Tuning Playbook](https://github.com/google-research/tuning_playbook)

### Exercises

- [Exercise 1](https://colab.research.google.com/github/fonsecamig/mpaaaf_course/blob/main/notebooks/exerc_mnist_hptuning.ipynb)
- [Exercise 2](https://colab.research.google.com/github/fonsecamig/mpaaaf_course/blob/main/notebooks/exerc_california_house_price.ipynb)

## Convolutional Neural Networks

- [Slides](slides/cnn.qmd)

### Reading

- Bishop, C. M., & Bishop, H. (2024). *Deep learning: Foundations and concepts.* Springer. [https://www.bishopbook.com](https://www.bishopbook.com)
  - Chapter 10: Convolutional Neural Networks
- Chollet, F. (2021). *Deep learning with Python (2nd ed.).* Manning Publications.
  - Chapter 8: Introduction to deep learning for computer vision
  - Chapter 9: Advanced deep learning for computer vision
- He, K., Zhang, X., Ren, S. & Sun, J. Deep Residual Learning for Image Recognition. 2016 IEEE Conf. Comput. Vis. Pattern Recognit. (CVPR) 770–778 (2016) [doi:10.1109/cvpr.2016.90](https://doi.org/10.1109/CVPR.2016.90).
- James, G., Witten, D., Hastie, T., Tibshirani, R., & Taylor, J. (2023). *An introduction to statistical learning: With applications in Python.* Springer. [https://www.statlearning.com](https://www.statlearning.com)
  - Chapter 10: Deep Learning
- Zhang, A., Lipton, Z. C., Li, M., & Smola, A. J. (2023). *Dive into deep learning.* Cambridge University Press. [https://d2l.ai](https://d2l.ai)
  - Chapter 8: Convolutional Neural Networks
  - Chapter 9: Modern Convolutional Neural Networks

### Exercises

- [Exercise 1](https://colab.research.google.com/github/fonsecamig/mpaaaf_course/blob/main/notebooks/exerc_cnn_mnist.ipynb)
- [Exercise 2](https://colab.research.google.com/github/fonsecamig/mpaaaf_course/blob/main/notebooks/exerc_1d_cnn_financial.ipynb)

## Recurrent Neural Networks

- [Slides](slides/rnn.qmd)

### Reading

- Chollet, F. (2021). *Deep learning with Python (2nd ed.).* Manning Publications.
  - Chapter 10: Deep learning for time series
- Zhang, A., Lipton, Z. C., Li, M., & Smola, A. J. (2023). *Dive into deep learning.* Cambridge University Press. [https://d2l.ai](https://d2l.ai)
  - Chapter 9: Recurrent Neural Networks
  - Chapter 10: Modern Recurrent Neural Networks

### Exercises

- [Exercise 1](https://colab.research.google.com/github/fonsecamig/mpaaaf_course/blob/main/notebooks/exerc_rnn_financial.ipynb)
- [Exercise 2](https://colab.research.google.com/github/fonsecamig/mpaaaf_course/blob/main/notebooks/exerc_rnn_wind.ipynb)
- [Exercise 3](https://colab.research.google.com/github/fonsecamig/mpaaaf_course/blob/main/notebooks/exerc_rnn_financial_direction.ipynb)

## Tokenization, Padding, Masking and Embeddings

- [Slides](slides/tokenization_pading_masking_embeddings.qmd)

### Reading

- Bishop, C. M., & Bishop, H. (2024). *Deep learning: Foundations and concepts.* Springer. [https://www.bishopbook.com](https://www.bishopbook.com)
  - Chapter 12: Transformers, Section 11.2
- Chollet, F. (2021). *Deep learning with Python (2nd ed.).* Manning Publications.
  - Chapter 11: Deep learning for text, Sections 11.1, 11.2 and 11.3
- Zhang, A., Lipton, Z. C., Li, M., & Smola, A. J. (2023). *Dive into deep learning.* Cambridge University Press. [https://d2l.ai](https://d2l.ai)
  - Chapter 9: Recurrent Neural Networks, Sections 9.1, 9.2 and 9.3
  - Chapter 15: Natural Language Processing: Pretraining
- [Code Example](https://colab.research.google.com/github/fonsecamig/mpaaaf_course/blob/main/notebooks/tf2_nlp_tokenization_notebook.ipynb)

### Exercises

- [Exercise 1](https://colab.research.google.com/github/fonsecamig/mpaaaf_course/blob/main/notebooks/exerc_rnn_imdb.ipynb)

## Transformers

### Attention

- [Slides](slides/transformers_attention_block.qmd)

### Decoders

- [Slides](slides/transformers_decoder.qmd)

### Encoders

- [Slides](slides/transformers_encoder.qmd)

### Reading

- Bishop, C. M., & Bishop, H. (2024). *Deep learning: Foundations and concepts.* Springer. [https://www.bishopbook.com](https://www.bishopbook.com)
  - Chapter 12: Transformers
- Chollet, F. (2021). *Deep learning with Python (2nd ed.).* Manning Publications.
  - Chapter 11: Deep learning for text
- Zhang, A., Lipton, Z. C., Li, M., & Smola, A. J. (2023). *Dive into deep learning.* Cambridge University Press. [https://d2l.ai](https://d2l.ai)
  - Chapter 11: Attention Mechanisms and Transformers
  - Chapter 15: Natural Language Processing: Pretraining


### Exercises

- [Exercise 1](https://colab.research.google.com/github/fonsecamig/mpaaaf_course/blob/main/notebooks/exerc_sequence_reverse.ipynb)
- [Exercise 2](https://colab.research.google.com/github/fonsecamig/mpaaaf_course/blob/main/notebooks/exerc_transformer_decoder.ipynb)
- [Exercise 3](https://colab.research.google.com/github/fonsecamig/mpaaaf_course/blob/main/notebooks/exerc_transformer_decoder_strategy.ipynb)
- [Exercise 4](https://colab.research.google.com/github/fonsecamig/mpaaaf_course/blob/main/notebooks/exerc_transformer_imdb.ipynb)
- [Exercise 5](https://colab.research.google.com/github/fonsecamig/mpaaaf_course/blob/main/notebooks/exerc_transformer_nlp.ipynb)

## Technical Indicators

- [Slides](slides/trading_indicators.qmd)

### Exercises

- [Exercise 1](https://colab.research.google.com/github/fonsecamig/mpaaaf_course/blob/main/notebooks/exerc_trading_indicators.ipynb)

## References

- Bishop, C. M., & Bishop, H. (2024). *Deep learning: Foundations and concepts.* Springer. [https://www.bishopbook.com](https://www.bishopbook.com)

- Chollet, F. (2021). *Deep learning with Python (2nd ed.).* Manning Publications.

- James, G., Witten, D., Hastie, T., Tibshirani, R., & Taylor, J. (2023). *An introduction to statistical learning: With applications in Python.* Springer. [https://www.statlearning.com](https://www.statlearning.com)

- Jansen, S. (2020). *Machine Learning for Algorithmic Trading.* Packt.

- Zhang, A., Lipton, Z. C., Li, M., & Smola, A. J. (2023). *Dive into deep learning.* Cambridge University Press. [https://d2l.ai](https://d2l.ai)